version: 2
updates:
  # Main package
  - package-ecosystem: "npm"
    directory: "/packages/yonode"
    schedule:
      interval: "weekly"
      day: "saturday"

  # Templates
  - package-ecosystem: "npm"
    directory: "/packages/yonode-templates/JS-MongoDB-Mongoose-Auth-Template"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/packages/yonode-templates/JS-MongoDB-Mongoose-NoAuth-Template"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/packages/yonode-templates/JS-MongoDB-Prisma-Auth-Template"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/packages/yonode-templates/JS-MongoDB-Prisma-NoAuth-Template"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/packages/yonode-templates/JS-MongoDB-TypeORM-Auth-Template"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/packages/yonode-templates/JS-MongoDB-TypeORM-NoAuth-Template"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/packages/yonode-templates/JS-MySQL-Prisma-Auth-Template"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/packages/yonode-templates/JS-MySQL-Prisma-NoAuth-Template"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/packages/yonode-templates/JS-MySQL-Sequelize-Auth-Template"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/packages/yonode-templates/JS-MySQL-Sequelize-NoAuth-Template"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/packages/yonode-templates/JS-MySQL-TypeORM-Auth-Template"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/packages/yonode-templates/JS-MySQL-TypeORM-NoAuth-Template"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/packages/yonode-templates/JS-PostgreSQL-Prisma-Auth-Template"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/packages/yonode-templates/JS-PostgreSQL-Prisma-NoAuth-Template"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/packages/yonode-templates/JS-PostgreSQL-Sequelize-Auth-Template"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/packages/yonode-templates/JS-PostgreSQL-Sequelize-NoAuth-Template"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/packages/yonode-templates/JS-PostgreSQL-TypeORM-Auth-Template"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/packages/yonode-templates/JS-PostgreSQL-TypeORM-NoAuth-Template"
    schedule:
      interval: "weekly"
      day: "saturday"

  # Branches
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "JS-MongoDB-Mongoose-Auth-Template"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "JS-MongoDB-Mongoose-NoAuth-Template"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "JS-MongoDB-Prisma-Auth-Template"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "JS-MongoDB-Prisma-NoAuth-Template"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "JS-MongoDB-TypeORM-Auth-Template"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "JS-MongoDB-TypeORM-NoAuth-Template"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "JS-MySQL-Prisma-Auth-Template"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "JS-MySQL-Prisma-NoAuth-Template"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "JS-MySQL-Sequelize-Auth-Template"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "JS-MySQL-Sequelize-NoAuth-Template"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "JS-MySQL-TypeORM-Auth-Template"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "JS-MySQL-TypeORM-NoAuth-Template"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "JS-PostgreSQL-Prisma-Auth-Template"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "JS-PostgreSQL-Prisma-NoAuth-Template"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "JS-PostgreSQL-Sequelize-Auth-Template"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "JS-PostgreSQL-Sequelize-NoAuth-Template"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "JS-PostgreSQL-TypeORM-Auth-Template"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "JS-PostgreSQL-TypeORM-NoAuth-Template"
