version: '3.9'

services:
  db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - '27017:27017'
    restart: on-failure
    # healthcheck:
    #   test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5


  server:
    build: .
    container_name: yonode-server
    restart: on-failure
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      NODE_ENVIRONMENT: ${NODE_ENVIRONMENT}
    depends_on:
      - db
      