version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: yonode
      POSTGRES_PASSWORD: 123321
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: on-failure:5

  server:
    build: .
    container_name: yonode-server
    restart: on-failure:5
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '8000:8000'
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_NAME: ${DATABASE_NAME}
      NODE_ENVIRONMENT: ${NODE_ENVIRONMENT}
    depends_on:
      - db